services:
  db-auth-services:
    image: mysql:8.0
    container_name: auth-service
    environment:
      MYSQL_DATABASE: auth-db
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3306:3306'
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
